[package]
name = "streamduck-core"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
async-trait = "0.1.58"
serde = { version = "1.0.147", features = ["derive"] }
futures = "0.3.25"